hosts_lm_cp2:
  - name: nfs
    ip: 192.168.1.115
    alias: nfs.lm.ar
  
  - name: master
    ip: 192.168.1.110
    alias: master.lm.ar

  - name: worker-01
    ip: 192.168.1.111
    alias:  worker-01.lm.ar

traffic_firewall:
  - key: net.bridge.bridge-nf-call-ip6tables
    value: 1
    
  - key: net.bridge.bridge-nf-call-iptables
    value: 1

  - key: net.ipv4.ip_forward
    value: 1

containers_repos: 
  - folder: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo 
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    
  - folder: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo 
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo

k8s_repos: 
  - line: '[kubernetes]'
  - line: name=Kubernetes
  - line: baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  - line: enabled=1
  - line: gpgcheck=1
  - line: repo_gpgcheck=1
  - line: gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - line: exclude=kubelet kubeadm kubectl

file_token: /home/lmachado/unir-cp2-lm/ansible/roles/worker/files/token.conf