ports_master_firewall:
  - port: 6443
    protocol: tcp
  
  - port: 2379-2380
    protocol: tcp

  - port: 10250-10252
    protocol: tcp

  - port: 10255
    protocol: tcp

  - port: 8285
    protocol: udp

  - port: 8472
    protocol: udp

firewall_workers_rules:
  - rule: 1
    family: ipv4
    source_address: 192.168.1.111/32
    target: accept

red_pods_k8s: 192.168.0.0/16

