- name: 0.1 - Crear el usuario {{ user_ansible }} 
  user: name={{ user_ansible }} append=yes state=present createhome=yes shell=/bin/bash

- name: Crear el archivo /etc/sudoers.d/{{ user_ansible }}
  ansible.builtin.file:
    path: /etc/sudoers.d/{{ user_ansible }}
    state: touch

- name: Permitir al {{ user_ansible }} realizar sudo sin clave
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the ansible user
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '{{ ssh_key }}') }}"