---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-calc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-calc-deployment
  namespace: webapp-calc
  labels:
    app: webapp-calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-calc
  template:
    metadata:
      labels:
        app: webapp-calc
    spec:
      containers:
      - name: webapp-calc
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        volumeMounts:
        - name: site-pvc
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site-pvc
        persistentVolumeClaim:
          claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: calc-service
    namespace: webapp-calc
spec:
    selector:
      app: webapp-calc
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calc-ingress
  namespace: webapp-calc
  labels:
    app: webapp-calc
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: master.lm.ar
  - http:
      paths:
      - path: /calc
        pathType: "Prefix"
        backend:
          service:
            name: calc-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: webapp-calc
data:
  servers-increment: "42"
  ssl-redirect: "OFF"