---
- name: 4.1 - Configurar usuario root para que pueda utilizar kubectl
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "KUBECONFIG="
    line: " KUBECONFIG=/etc/kubernetes/admin.conf"
---
- name: 4.2 - Configurar acceso al cluster
  file:
    path: $HOME/.kube
    state: directory

- name: 4.3 - Copiar archivo /.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root
    group: root