---
- name: 8 - Reiniciar master
  reboot:
    msg: "Reinicio luego de instalar k8s"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: yes