---
- name: Despliegue nodo master
  hosts: master
  become: true
  vars_files:
    - "groups_vars/common.yaml"
    - "groups_vars/k8s.yaml"
    - "groups_vars/master.yaml"
    - "groups_vars/webapp.yaml"
  gather_facts: false
  roles:
    - common
    - k8s
    - master 
    - webapp