---
- name: Despliegue nodos workers
  hosts: workers
  become: true
  vars_files:
    - "groups_vars/common.yaml"
    - "groups_vars/k8s.yaml"
    - "groups_vars/worker.yaml"
  gather_facts: false
  roles:
    - common
    - k8s
    - worker