---
- name: 8 - Reiniciar worker
  reboot:
    msg: "Reinicio luego deL JOIN"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: yes