---
- name: 1 - Agregar Hosts de la solución al archivo /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}$'
    line: '{{ item.ip }} {{ item.name }} {{ item.alias }}'
    state: present
  with_items: '{{ hosts_lm_cp2 }}'
