---
- name: 2.1 - Habilitar e iniciar el servicio firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: 2.2 - Deshabilitar AllowZoneDrifting
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: 'AllowZoneDrifting.*'
    line: 'AllowZoneDrifting:no'
    state: present
  become: yes