---
- name: 2.1 - Habilitar e iniciar el servicio firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: 2.2 - Deshabilitar opción AllowZoneDrifting
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: 'AllowZoneDrifting.*'
    line: 'AllowZoneDrifting=no'
    state: present

- name: 2.3 - Reiniciar el servicio firewalld
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld