---
- name: 4.1 - Deshabilitar swap
  command: swapoff  -a
 
- name: 4.2 - Eliminar archivo el mount del /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '.*/dev/mapper/cs-swap.*'
    line: ''
    state: present