- name: 5.1 - Descargar repositorios cri-o
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.folder }}'
  loop: '{{ containers_repos }}'
  become: yes

- name: 'Copio archivo para config CRI-O'
  copy:
    src: 'crio.conf'
    dest: '/etc/modules-load.d/'
  become: yes
  become_method: sudo

  
- name: 'instalo CRI-O'
  dnf:
    name: 'cri-o'
    state: present
  become: yes
  become_method: sudo

- name: 'Inicializa servicio y setea inicio automatico para servicio cri-o'
  systemd:
    name: 'crio'
    state: started
    enabled: yes
  become: yes
  become_method: sudo

