---
- name: 7.1 - Instalar kubelet,kubeadm y kubectl
  dnf:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes
    state: present

- name: 7.2 - Iniciar servicio kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes